-- 0021_nodes_disk_usage.sql：节点磁盘容量统计（根分区与 /home）

ALTER TABLE nodes
    ADD COLUMN IF NOT EXISTS disk_total_gb DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS disk_used_gb DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS home_total_gb DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS home_used_gb DOUBLE PRECISION NOT NULL DEFAULT 0;

