ALTER TABLE ssh_whitelist
  ADD COLUMN IF NOT EXISTS reason TEXT NOT NULL DEFAULT '';

ALTER TABLE ssh_blacklist
  ADD COLUMN IF NOT EXISTS reason TEXT NOT NULL DEFAULT '';

ALTER TABLE ssh_exemptions
  ADD COLUMN IF NOT EXISTS reason TEXT NOT NULL DEFAULT '';
