ALTER TABLE admin_accounts
  ADD COLUMN IF NOT EXISTS two_factor_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS two_factor_secret TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS two_factor_pending_secret TEXT NOT NULL DEFAULT '';

ALTER TABLE power_users
  ADD COLUMN IF NOT EXISTS two_factor_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS two_factor_secret TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS two_factor_pending_secret TEXT NOT NULL DEFAULT '';

ALTER TABLE user_accounts
  ADD COLUMN IF NOT EXISTS two_factor_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS two_factor_secret TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS two_factor_pending_secret TEXT NOT NULL DEFAULT '';
